### ISSUE TITLE
New posts aren't being added to the users posts array.

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#1]

**Comment by braydenidzenga** [comment]
> plzz assign to me this issue

going to assign this issue to you. Please add it so that when the user creates a post it adds it to the users post array and increments the postCount value by 1.

**Comment by Anurag12133** [comment]
sure by eod i raise my PR

**Comment by Anurag12133** [comment]
i just want to know that in your newPost function postcunt of user i need to be added or not ? or just i need to update in backend when it is required it can fetched correctly if user 1 have 3 post then count is 3 like this?

**Comment by braydenidzenga** [comment]
The count should be the amount of posts the user has made. If the user creates a post it should go up by 1 and if a user deletes a post it should go down by 1

**Comment by Anurag12133** [comment]
![image](https://github.com/user-attachments/assets/f0cf258b-c98e-456a-a8fc-578b8d23d395)

on increment

**Comment by braydenidzenga** [comment]
Yes
