### ISSUE TITLE
Come up with a new name for the project.

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#15]
This project is for a social media platform made for programmers. I am not very good with coming up with names for my projects. If you have any naming suggestions please leave a comment under this issue.

**Comment by Anurag12133** [comment]
assign me this

**Comment by Anurag12133** [comment]
Will give u name tommorow morning

**Comment by braydenidzenga** [comment]
@Anurag12133 this issue is going to just be used to comment name suggestions.

**Comment by iamDyeus** [comment]
- Modro
- Doovio

**Comment by 5ucl33p** [comment]
codagram
dev-love-ment 
codub
brogram (bro in place of pro)
codacity

**Comment by kiinshuk** [comment]
1. Codak
2. TIM
3. SMPC - Social Media Platform for Coders.
4. Bugchat
5. bugger
6. programmatio (latin word for programing)

**Comment by braydenidzenga** [comment]
I have decided to go forward with the name brogram

**Comment by Anurag12133** [comment]
Voxen is better one
