### ISSUE TITLE
Disallow user names with spaces

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#16]
Disallow users to signup using username that have spaces in them. Only allow usernames with the characters [a-z] and underscores, dashes, and periods.

**Comment by sikehish** [comment]
I'd like to take this up as well :)

**Comment by braydenidzenga** [comment]
I will assign both of those issues to you. Please try to get a pr up as soon as possible.

**Comment by MohitKambli** [comment]
Hello,
I would like to work on this issue too!

Thanks and Regards,
Mohit Kambli

**Comment by sikehish** [comment]
Hi. I was assigned to this issue. Is everything alright?
