### ISSUE TITLE
Password regex

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#17]
only allow users to signup with passwords that are at least 12 characters long and have one special character and one number in it.

**Comment by sikehish** [comment]
I'd like to take this up.

**Comment by sikehish** [comment]
I'm working on this.

**Comment by sikehish** [comment]
Hi @braydenidzenga.
Ive raised a PR #21. Do let me know if any changes are to be made.
Thanks for the oppurtunity!
