### ISSUE TITLE
Stop user from logging in if the user is banned.

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#2]

**Comment by nidhi752** [comment]
hey, I am unable to start this on my local machine. Can you please help?

**Comment by braydenidzenga** [comment]
> hey, @braydenidzenga I am unable to start this on my local machine. Can you please help?

Have you followed all the steps in the setup documentation?

**Comment by NagapavanTechWorm** [comment]
Hi @braydenidzenga,

I'd love to contribute to this issue! I can help by implementing a check in the login process to prevent banned users from accessing the system. I’ll start by adding a validation step that checks the user’s status in the database before allowing login attempts.

Let me know if this approach works for you, and I can begin working on it!

**Comment by nidhi752** [comment]
@braydenidzenga hi yes, I have done almost everything. It's not working.

**Comment by braydenidzenga** [comment]
> @braydenidzenga hi yes, I have done almost everything. It's not working.

Can you send a screen shot of the error

**Comment by nidhi752** [comment]
![image](https://github.com/user-attachments/assets/515ba8f0-2843-4860-bc97-9a2689b6159e)

**Comment by braydenidzenga** [comment]
> ![image](https://github.com/user-attachments/assets/515ba8f0-2843-4860-bc97-9a2689b6159e)
> 
> 

Check that your mongodb connection string is right since it's an issue connecting to the database

**Comment by nidhi752** [comment]
I have checked and confirmed it several times.

**Comment by NagapavanTechWorm** [comment]
@nidhi752 Inside the `api`  folder, create a `.env` file and add the MongoDB URL. Use an example URL like this: `mongodb+srv://<username>:<password>@100xdev.4iu3b.mongodb.net/`. At the end, specify the collection as `Dialogue` or your wish, for example: `mongodb+srv://<username>:<password>@100xdev.4iu3b.mongodb.net/Dialogue`.

**Comment by nidhi752** [comment]
![image](https://github.com/user-attachments/assets/acce3a3d-b6cd-4dcc-bd28-8ff53a75afb7)


now i can't see where this is working
