### ISSUE TITLE
User profile pictures

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#5]
Create a way for users to set a profile picture and have a default picture for users who hasn't set one yet.

**Comment by braydenidzenga** [comment]
@Bamof25th would you be able to breakdown your approach to implementing this before I assign you the issue.

**Comment by Bamof25th** [comment]
ok will update the user model  -   

 => profilePicture: {
      type: String,
      default:
        "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
    },

and  will update the signup and other controllers accordingly.

**Comment by braydenidzenga** [comment]
@Bamof25th 

Sounds good to me. I will assign this issue to you, please try and get this done as soon as possible.

**Comment by Bamof25th** [comment]
ok

**Comment by Bamof25th** [comment]
Done check, please ✅ 

Add user profile picture functionality with default avatar for users without a custom picture
currently : 

- > added a default url for the default avatar as a user profile picture.
- > updated the user model  accordingly 
- > fixed typo in modal in password section
