### ISSUE TITLE
Get user profile

### ISSUE THREAD

**Issue by braydenidzenga** [braydenidzenga/Dev-Dialogue#6]
Please create a route that when given a userId it will fetch that given user from the database and return public information such as post count, follower count, name, and username. Please do not return any sensitive information such as emails or passwords.

Please comment how you are going to approach implementing this before the issue will be assigned to you

**Comment by Anurag12133** [comment]
assign to me this issue also i can fix this

**Comment by braydenidzenga** [comment]
> assign to me this issue also i can fix this

@Anurag12133 I will assign you this also. Please try and get these two issues completed as soon as possible.

**Comment by codewithjk** [comment]
1. we will get the user id from the endpoint as params
2. in the users / controller  , create a getProfile method
3. in that method we can import the user schema and query using id . and filter out the public data.
assign to me

**Comment by braydenidzenga** [comment]
> 1. we will get the user id from the endpoint as params
> 
> 2. in the users / controller  , create a getProfile method
> 
> 3. in that method we can import the user schema and query using id . and filter out the public data.
> 
> assign to me
> 
> 

Sorry but I have already assigned this issue to somebody. If you would like I can ping you in future issues.

**Comment by Bamof25th** [comment]
ok no problem

**Comment by Anurag12133** [comment]
no woorries do it by eod
